const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');fs.mkdirSync('test-results',{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const routes=['overview',...Array.from({length:10},(_,i)=>'journey/M'+i),'programs',...['pre','dic','growth','tasmu','scale','alumni'].map(x=>'program/'+x),...['E1','E2','E3','E4','E5','X1','X2','X3','X4','X5'].map(x=>'gates/'+x),'simulator/E3','routing/growth','routing/tasmu','services','services/service-9','compare','kpis','logic','glossary','source','editor'];
for(const route of routes){await page.goto('http://localhost:4174/#/'+route);await page.locator('h1').waitFor();await page.waitForTimeout(120);assert.ok(!(await page.locator('h1').innerText()).includes('encountered an error'));if(['overview','programs','gates/E3','routing/growth'].includes(route))await page.screenshot({path:'test-results/'+route.replaceAll('/','-')+'.png'});}
await page.goto('http://localhost:4174/#/program/dic');for(const t of ['Interventions & milestones','Entry & exit','Outcomes & routing','Thesis & fit']){await page.getByRole('button',{name:t,exact:true}).click();await page.waitForTimeout(100);}
await page.goto('http://localhost:4174/#/gates/E3');await page.locator('.criterion summary').first().click();assert.ok(await page.getByText('Required evidence',{exact:true}).first().isVisible());
await page.goto('http://localhost:4174/#/simulator/E3');await page.locator('.check-row select').first().selectOption('does-not-meet');assert.ok((await page.locator('.live-result').innerText()).includes('Not yet eligible'));
await page.getByRole('button',{name:'View mode',exact:true}).click();await page.getByRole('button',{name:'Enable Edit mode',exact:true}).click();await page.evaluate(()=>location.hash='/editor');await page.locator('.entity-actions button').first().click();await page.getByLabel('Short Name',{exact:true}).fill('Edited Pre-incubation');await page.getByRole('button',{name:'Save revision',exact:true}).click();await page.waitForTimeout(200);await page.reload();await page.locator('h1').waitFor();
const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('mcit-architecture-workspace-v1')));assert.equal(saved.programs[0].shortName,'Edited Pre-incubation');
await page.getByRole('button',{name:'Present',exact:true}).click();assert.ok(await page.locator('.presentation').count());assert.equal(await page.locator('.edit-link').count(),0);await page.keyboard.press('ArrowRight');await page.waitForTimeout(150);assert.ok(page.url().endsWith('journey/M0'));await page.keyboard.press('Escape');assert.equal(await page.locator('.presentation').count(),0);
for(const width of [1920,1024,390]){await page.setViewportSize({width,height:1000});for(const route of ['overview','programs','gates/E3','simulator/E3','routing/growth','kpis','compare']){await page.goto('http://localhost:4174/#/'+route);await page.locator('h1').waitFor();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);assert.equal(overflow,false,'Page overflow '+width+' '+route);}await page.screenshot({path:'test-results/responsive-'+width+'.png'});}
await page.emulateMedia({reducedMotion:'reduce'});await page.goto('http://localhost:4174/#/overview');await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.activeElement.tagName!=='BODY'));assert.deepEqual(errors,[]);await browser.close();console.log(JSON.stringify({routes:routes.length,responsiveWidths:[1920,1024,390],checks:['program tabs','gate expansion','simulator failure','edit/save/reload','presentation keyboard','reduced motion','no runtime errors'],status:'PASS'},null,2));})().catch(e=>{console.error(e);process.exit(1)});
