import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {validateFramework,byId,resolve,evaluateGate} from '../src/lib/model.js';
const d=JSON.parse(fs.readFileSync(new URL('../src/data/framework.json',import.meta.url)));
const check=(id,a={})=>{const g=byId(d.gates,id);return evaluateGate(g,resolve(d.criteria,g.criterionIds),a);};
const pass=id=>Object.fromEntries(resolve(d.criteria,byId(d.gates,id).criterionIds).map(c=>[c.id,{state:'meets',evidence:'verified'}]));
test('All structured references validate',()=>assert.deepEqual(validateFramework(d),[]));
test('Ten maturity stages, six program propositions, ten gates',()=>{assert.equal(d.stages.length,10);assert.equal(d.programs.length,6);assert.equal(d.gates.length,10);});
test('All 16 source sections retained',()=>assert.equal(d.sections.length,16));
test('JSON round trip is lossless',()=>assert.deepEqual(JSON.parse(JSON.stringify(d)),d));
test('Malformed import rejected',()=>assert.ok(validateFramework({schemaVersion:1}).length));
test('Broken relationships rejected',()=>{const x=structuredClone(d);x.programs[0].startStageId='missing';assert.ok(validateFramework(x).length);});
test('Scenario A: no MVP does not disqualify Incubation entry',()=>assert.equal(check('E2',pass('E2')).status,'Mandatory conditions met'));
test('Scenario B: product and users without paid demand do not qualify for Local Growth',()=>{const a=pass('E3');a['E3-criterion-1'].state='does-not-meet';assert.equal(check('E3',a).status,'Not yet eligible');});
test('Scenario C: PMF alone does not qualify for Scale Now',()=>{const a=pass('E5');a['E5-criterion-1'].state='does-not-meet';assert.equal(check('E5',a).status,'Not yet eligible');});
test('Scenario D: X3 graduation is independent of E5 capital',()=>{assert.equal(check('X3',pass('X3')).status,'Graduation requirements met');const a=pass('E5');a['E5-criterion-3'].state='does-not-meet';assert.equal(check('E5',a).status,'Not yet eligible');});
test('Unverified mandatory evidence never passes',()=>{const a=pass('E1');a['E1-criterion-1'].evidence='submitted';assert.equal(check('E1',a).status,'Evidence / exception review required');});
test('Not applicable mandatory condition requires review',()=>{const a=pass('E1');a['E1-criterion-1'].state='not-applicable';assert.equal(check('E1',a).status,'Evidence / exception review required');});
test('X1 lower-maturity graduation conflict is flagged',()=>{const a=pass('X1');a['X1-criterion-2'].state='does-not-meet';const r=check('X1',a);assert.equal(r.conflicts.length,1);assert.equal(r.status,'Mandatory exit requirements not met');});
test('No weighted score invented for incomplete E2/E4 weights',()=>{assert.ok(!('score' in check('E2',pass('E2'))));assert.ok(!('score' in check('E4',pass('E4'))));});
test('Completion-only requirement is separate from graduation',()=>{const a=pass('X1');a['X1-criterion-4'].state='does-not-meet';assert.equal(check('X1',a).status,'Graduation requirements met');});
