import React,{useState} from 'react';
import {useFramework} from '../lib/context';
import {collections,byId,validateFramework,getIncomingReferences,downloadJSON} from '../lib/model';
import {Heading,Modal,Note,Icon,Empty} from './common';
const human=s=>s.replace(/([A-Z])/g,' $1').replaceAll('-',' ').replace(/^./,x=>x.toUpperCase());
export function EntityEditor({collection,entity,onClose,isNew=false}){
 const {data,commit}=useFramework();const [draft,setDraft]=useState(structuredClone(entity)),[error,setError]=useState('');
 const set=(key,val)=>setDraft(d=>({...d,[key]:val}));
 async function save(e){e.preventDefault();try{const next=structuredClone(data);if(isNew)next[collection].push(draft);else next[collection]=next[collection].map(x=>x.id===entity.id?draft:x);
  // Keep explicit ownership links coherent when an entity is created or moved.
  const ownership={criteria:['gates','gateId','criterionIds'],interventions:['programs','programId','interventionIds'],milestones:['programs','programId','milestoneIds'],outcomes:['programs','programId','outcomeIds']};
  if(ownership[collection]){const [target,field,arr]=ownership[collection];for(const parent of next[target]){if(parent.id!==draft[field])parent[arr]=parent[arr].filter(id=>id!==draft.id);else if(!parent[arr].includes(draft.id))parent[arr].push(draft.id);}}
  if(collection==='gates'){for(const p of next.programs){p.entryGateIds=p.entryGateIds.filter(id=>id!==draft.id);p.exitGateIds=p.exitGateIds.filter(id=>id!==draft.id);if(p.id===draft.programId)p[draft.kind==='entry'?'entryGateIds':'exitGateIds'].push(draft.id);}}
  if(collection==='routes'){for(const p of next.programs){p.routeIds=p.routeIds.filter(id=>id!==draft.id);if(p.id===draft.fromId)p.routeIds.push(draft.id);}}
  await commit(next);onClose();}catch(e){setError(e.message);}}
 return <Modal title={`${isNew?'Add':'Edit'} ${human(collection)}`} onClose={onClose} wide><form onSubmit={save}><Note title="Local working revision">Approved source wording remains in the reference archive. Changes are saved only in this browser; this is not authenticated access control.</Note><div className="editor-form">{Object.entries(draft).map(([key,value])=>Array.isArray(value)?<fieldset key={key}><legend>{human(key)} · relationship IDs</legend>{value.map((v,i)=><div className="array-editor" key={i}><input aria-label={`${key} item ${i+1}`} value={v} onChange={e=>set(key,value.map((x,j)=>j===i?e.target.value:x))}/><button type="button" disabled={i===0} aria-label={`Move ${v} up`} onClick={()=>{const a=[...value];[a[i-1],a[i]]=[a[i],a[i-1]];set(key,a);}}>↑</button><button type="button" disabled={i===value.length-1} aria-label={`Move ${v} down`} onClick={()=>{const a=[...value];[a[i+1],a[i]]=[a[i],a[i+1]];set(key,a);}}>↓</button><button type="button" aria-label={`Remove relationship ${v}`} onClick={()=>set(key,value.filter((_,j)=>j!==i))}>×</button></div>)}<button type="button" onClick={()=>set(key,[...value,''])}>Add relationship</button></fieldset>:<label className="control" key={key}>{human(key)}{typeof value==='number'?<input type="number" value={value} onChange={e=>set(key,Number(e.target.value))}/>:key==='id'?<input required disabled={!isNew} value={value} onChange={e=>set(key,e.target.value)}/>:key==='color'?<input type="color" value={value} onChange={e=>set(key,e.target.value)}/>:<textarea aria-label={human(key)} rows={String(value).length>100?4:2} value={value??''} onChange={e=>set(key,e.target.value)}/>}</label>)}</div>{error&&<pre className="error" role="alert">{error}</pre>}<div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" type="submit">Save revision <Icon name="check"/></button></div></form></Modal>
}
export function Editor({onEdit}){const {data,edit,commit,undo,reset,canUndo}=useFramework();const [collection,setCollection]=useState('programs'),[q,setQ]=useState(''),[error,setError]=useState('');const items=data[collection].filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));
 function add(){const template=structuredClone(data[collection][0]||{id:'',name:'',description:''});for(const key of Object.keys(template)){if(Array.isArray(template[key]))template[key]=[];else if(typeof template[key]==='string'&&!key.endsWith('Id')&&!['type','kind','color','tier'].includes(key))template[key]='';}template.id=`${collection}-${Date.now()}`;template.name='New '+collection.replace(/s$/,'');onEdit(collection,template,true);}
 async function move(id,delta){try{const next=structuredClone(data);const a=next[collection],i=a.findIndex(x=>x.id===id),j=i+delta;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];if(collection==='stages')a.forEach((x,i)=>x.order=i);await commit(next);}catch(e){setError(e.message);}}
 async function remove(item){if(!window.confirm(`Delete ${item.name}? This affects the local working revision only.`))return;try{const next=structuredClone(data);const removable=['criteria','interventions','milestones','outcomes','kpis'];if(removable.includes(collection)){for(const key of collections)for(const x of next[key])for(const [f,v]of Object.entries(x))if(Array.isArray(v)&&f.endsWith('Ids'))x[f]=v.filter(id=>id!==item.id);}
 const refs=getIncomingReferences(next,collection,item.id);if(refs.length)throw new Error('Deletion blocked to preserve relationships. Remove these references first:\n'+refs.join('\n'));next[collection]=next[collection].filter(x=>x.id!==item.id);await commit(next);}catch(e){setError(e.message);}}
 async function importFile(e){try{const file=e.target.files[0];if(!file)return;if(file.size>10000000)throw new Error('Framework file exceeds the 10 MB limit.');const d=JSON.parse(await file.text());const errors=validateFramework(d);if(errors.length)throw new Error(errors.join('\n'));if(!window.confirm('Replace the current workspace? Export a backup first if needed.'))return;await commit(d);setError('');}catch(e){setError(e.message);}finally{e.target.value='';}}
 return <><Heading eyebrow="FRAMEWORK STUDIO / LOCAL WORKING REVISION" title="Edit the model. The views follow." description="Structured entities and explicit relationships drive every visualization."/><Note title="Storage and authorization">Changes persist in this browser only. Other browsers and colleagues do not receive them. Edit mode is not secure authorization; use JSON exports to transfer revisions until an authenticated backend is added.</Note><div className="toolbar"><button onClick={()=>downloadJSON(data,'entrepreneurship-framework.json')}>Export framework <Icon name="download"/></button>{edit&&<><label className="file-button">Import framework<input type="file" accept=".json,application/json" onChange={importFile}/></label><button disabled={!canUndo} onClick={()=>undo().catch(e=>setError(e.message))}>Undo last revision</button><button onClick={()=>{if(window.confirm('Restore original source data? Export your workspace first.'))reset().catch(e=>setError(e.message));}}>Restore source</button></>}</div>{!edit?<Empty text="Enable Edit mode to add, edit, delete, reorder or import framework entities."/>:<><div className="toolbar"><label className="control">Entity collection<select value={collection} onChange={e=>setCollection(e.target.value)}>{collections.map(k=><option key={k} value={k}>{human(k)} ({data[k].length})</option>)}</select></label><label className="search-box"><Icon name="search"/><input aria-label="Search editable entities" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search content or ID"/></label><button className="primary" onClick={add}>Add entity <Icon name="plus"/></button></div>{error&&<pre className="error" role="alert">{error}</pre>}<div className="entity-list">{items.map(x=><article key={x.id}><div><small>{x.id}</small><h3>{x.name}</h3><p>{x.description||x.definition||x['strategic-objective']||x.evidence||x.rule||''}</p></div><div className="entity-actions"><button onClick={()=>onEdit(collection,x)}>Edit</button><button aria-label={`Move ${x.name} up`} onClick={()=>move(x.id,-1)}>↑</button><button aria-label={`Move ${x.name} down`} onClick={()=>move(x.id,1)}>↓</button><button className="danger" onClick={()=>remove(x)}>Delete</button></div></article>)}</div><details className="criterion"><summary><strong>Relationship ID directory</strong><Icon name="chevron"/></summary><div className="criterion-content"><p>Use these IDs when adding or reordering relationships. Invalid references are rejected before saving.</p>{collections.map(k=><p key={k}><b>{human(k)}:</b> {data[k].map(x=>x.id).join(', ')}</p>)}</div></details></>}</>}
