import React,{useState} from 'react';
import {motion} from 'framer-motion';
import {useFramework} from '../lib/context';
import {byId} from '../lib/model';
import {Heading,Icon,Field,Note,Source,EditButton,Empty} from './common';
export function StageNode({stage,selected,onSelect}){return <button className={`stage-node ${selected?'selected':''}`} onClick={()=>onSelect(stage.id)} aria-pressed={selected} title={stage.question}><span className="stage-dot">{stage.id}</span><strong>{stage.name}</strong><small>{stage.phase}</small></button>}
export function JourneyMap({data,selected,onSelect,compact=false}){return <div className={`journey-scroll ${compact?'compact':''}`}><div className="journey-map">{data.stages.map(s=><StageNode key={s.id} stage={s} selected={s.id===selected} onSelect={onSelect}/>)}</div></div>}
export function ProgramBand({program,data,onSelect}){const start=data.stages.findIndex(s=>s.id===program.startStageId),end=data.stages.findIndex(s=>s.id===program.endStageId);return <div className="band-row"><button className="band-label" onClick={()=>onSelect(program.id)}><i style={{background:program.color}}/><strong>{program.shortName}</strong><small>{program.marketPositionId}</small></button><div className="band-track" style={{gridTemplateColumns:`repeat(${data.stages.length},1fr)`}}><button className="program-band" style={{gridColumn:`${start+1} / ${end+2}`,borderColor:program.color,background:program.color+'12',color:program.color}} onClick={()=>onSelect(program.id)}><span>{program.entryGateIds.join(' / ')||'Membership'}</span><strong>{program.type==='soft-landing'?'Venture M6+ | Qatar M2-M5':`${program.startStageId} → ${program.endStageId}`}</strong><span>{program.exitGateIds.join(' / ')||'Re-entry'}</span></button></div></div>}
export function Overview({navigate}){const {data}=useFramework();const [selected,setSelected]=useState('dic');const p=byId(data.programs,selected)||data.programs[0];return <>
 <Heading eyebrow="THE PORTFOLIO / EXECUTIVE VIEW" title="One journey. Evidence at every step." description="Programs are interventions in a startup’s development, not the definition of its maturity."/>
 <div className="overview-statement"><span className="section-index">01</span><div><h2>From a testable idea to a repeatable business.</h2><p>{data.sections[1].blocks.find(b=>b.kind==='text')?.text.replace('Thesis: ','')}</p></div><button className="primary" onClick={()=>navigate('journey')}>Explore the journey <Icon/></button></div>
 <div className="system-map"><div className="map-top"><h2>The Qatar-anchored pathway</h2><span>Direct entry at any verified maturity</span></div><JourneyMap data={data} onSelect={id=>navigate('journey/'+id)} compact/>
 <div className="pathway-programs">{data.programs.filter(p=>!['soft-landing','relationship'].includes(p.type)).map(p=><button key={p.id} className={`path-program ${selected===p.id?'active':''}`} style={{'--program':p.color}} onClick={()=>setSelected(p.id)}><small>{p.entryGateIds.join(' / ')} → {p.exitGateIds.join(' / ')}</small><strong>{p.shortName}</strong><span>{p.startStageId} → {p.endStageId}</span><Icon/></button>)}</div>
 <div className="international-lane"><span className="lane-label">INTERNATIONAL ENTRY</span><button onClick={()=>navigate('program/tasmu')}>TASMU Soft Landing <small>Venture M6+ · Qatar market M2–M5</small></button><span>→</span><p>Market Access + alumni; Scale Now only after anchoring and E5.</p></div>
 <div className="shared-rail"><span>HORIZONTAL SUPPORT</span>{[1,3,9,8].map(n=>{const s=byId(data.services,'service-'+n);return s&&<button key={s.id} onClick={()=>navigate('services/'+s.id)}>{s.form.includes('Capital')?'Capital Readiness':s.form.includes('Market Access')?'Market Access':s.name.includes('Legal')?'Regulatory Navigator':'Technology & Product'} <Icon size={14}/></button>})}</div></div>
 {p&&<motion.div className="context-strip" key={p.id} initial={{opacity:0}} animate={{opacity:1}}><div><span className="eyebrow" style={{color:p.color}}>{p.shortName}</span><h3>{p['strategic-objective']}</h3></div><button onClick={()=>navigate('program/'+p.id)}>Open architecture <Icon/></button></motion.div>}
 <div className="principles-row"><div><b>Completion</b><span>Participation obligations met</span></div><strong>≠</strong><div><b>Graduation</b><span>Mandatory exit evidence verified</span></div><strong>≠</strong><div><b>Qualification</b><span>Next entry gate independently met</span></div></div><Source section="3;5;8.1;16"/>
 </>}
export function Journey({id,navigate,onEdit}){const {data}=useFramework();const s=byId(data.stages,id)||data.stages[0];if(!s)return <Empty/>;const related=data.programs.filter(p=>p.type!=='relationship'&&s.order>=byId(data.stages,p.startStageId)?.order&&s.order<=byId(data.stages,p.endStageId)?.order);return <><Heading eyebrow="STARTUP JOURNEY / MATURITY" title="Progress is proven, not attended." description="Select a maturity stage to reveal its objective, evidence and appropriate intervention."/><JourneyMap data={data} selected={s.id} onSelect={id=>navigate('journey/'+id)}/><motion.section className="stage-detail" key={s.id} initial={{opacity:0}} animate={{opacity:1}}><div className="stage-detail-title"><span className="large-stage">{s.id}</span><div><div className="eyebrow">{s.phase}</div><h2>{s.name}</h2><p className="question">{s.question}</p></div><EditButton collection="stages" entity={s} onEdit={onEdit}/></div><div className="detail-columns"><div><Field label="Primary objective" value={s['primary-objective']}/><Field label="What must be true" value={s['what-must-be-true']}/><Field label="Expected evidence" value={s['expected-evidence']}/><Note title="Milestone to progress">{s['milestone-to-progress']}</Note></div><div><Field label="Founder challenges" value={s['founder-challenges']}/><Field label="Key risks" value={s['key-risks']}/><Field label="Justified interventions" value={s['justified-interventions']}/><Field label="Next destinations" value={s['next-destinations']}/></div></div><h3>Relevant intervention bands</h3><div className="inline-links">{related.map(p=><button key={p.id} onClick={()=>navigate('program/'+p.id)} style={{borderLeftColor:p.color}}>{p.shortName}<small>{p['maturity-at-entry']}</small><Icon/></button>)}</div><Source section="3;4;5"/></motion.section></>}
export function Portfolio({navigate}){const {data}=useFramework();const [type,setType]=useState('all'),[stage,setStage]=useState('all');const ps=data.programs.filter(p=>(type==='all'||p.type===type)&&(stage==='all'||byId(data.stages,stage)?.order>=byId(data.stages,p.startStageId)?.order&&byId(data.stages,stage)?.order<=byId(data.stages,p.endStageId)?.order));return <><Heading eyebrow="PROGRAM PORTFOLIO / MATURITY BANDS" title="Different jobs. One coherent system." description="Read each band as a support mandate, not automatic admission or graduation."/><div className="toolbar"><label className="control">Program type<select value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option>{[...new Set(data.programs.map(p=>p.type))].map(t=><option key={t}>{t}</option>)}</select></label><label className="control">Maturity stage<select value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All stages</option>{data.stages.map(s=><option key={s.id} value={s.id}>{s.id} · {s.name}</option>)}</select></label><button onClick={()=>navigate('compare')}>Compare programs <Icon name="compare"/></button></div><div className="portfolio-scroll"><div className="portfolio-matrix"><div className="matrix-axis"><span>PROGRAM / MARKET AXIS</span><div>{data.stages.map(s=><button key={s.id} onClick={()=>navigate('journey/'+s.id)}>{s.id}<small>{s.name}</small></button>)}</div></div>{ps.map(p=><ProgramBand key={p.id} program={p} data={data} onSelect={id=>navigate('program/'+id)}/>)}</div></div>{!ps.length&&<Empty/>}<Note title="Two axes prevent false overlap">TASMU’s band reflects venture maturity. Its Qatar-market journey is M2–M5. Scale Now requires M7+ at home and measures evidence separately in each target market.</Note><div className="detail-columns"><Field label="Local Growth: aspiration versus exit" value="Target band M5–M7; mandatory X3 exit is M6 plus improving unit economics. M7 is directional, not automatic."/><Field label="Alumni is a relationship, not a maturity stage" value={data.programs.find(p=>p.id==='alumni')?.['program-thesis']}/></div><Source section="3;5;8.2;16"/></>}
