import React,{useState} from 'react';
import {useFramework} from '../lib/context';
import {byId,resolve} from '../lib/model';
import {Heading,Field,Note,Icon,Source,EditButton,Table,Empty} from './common';
export function MilestoneSequence({items,onEdit}){return <ol className="milestone-sequence">{items.map((m,i)=><li key={m.id}><span>{String(i+1).padStart(2,'0')}</span><div><p>{m.name}</p><EditButton collection="milestones" entity={m} onEdit={onEdit}/></div></li>)}</ol>}
export function ProgramDetail({id,navigate,onEdit}){const {data}=useFramework();const p=byId(data.programs,id);const [tab,setTab]=useState('thesis');if(!p)return <Empty text="Program not found. Return to the portfolio."/>;const tabs=[['thesis','Thesis & fit'],['delivery','Interventions & milestones'],['gates','Entry & exit'],['outcomes','Outcomes & routing']];return <>
 <Heading eyebrow={`PROGRAM ARCHITECTURE / ${p.type.toUpperCase()}`} title={p.name} description={p['strategic-objective']}><EditButton collection="programs" entity={p} onEdit={onEdit}/><button onClick={()=>navigate('compare')}>Compare <Icon name="compare"/></button></Heading>
 <div className="program-summary" style={{borderColor:p.color}}><div><span>MATURITY AT ENTRY</span><strong>{p['maturity-at-entry']}</strong></div><div><span>MARKET AXIS</span><strong>{p.marketPositionId}</strong></div><div><span>ENTRY GATE</span><strong>{p.entryGateIds.join(' / ')||'Completion-based membership'}</strong></div><div><span>EXIT GATE</span><strong>{p.exitGateIds.join(' / ')||'Annual good standing'}</strong></div></div>
 <nav className="tabs" aria-label="Program sections">{tabs.map(([key,label])=><button key={key} className={tab===key?'active':''} aria-current={tab===key?'page':undefined} onClick={()=>setTab(key)}>{label}</button>)}</nav>
 {tab==='thesis'&&<><div className="thesis"><span className="eyebrow">PROGRAM THESIS</span><h2>{p['program-thesis']}</h2></div><div className="detail-columns"><div><Field label="Why this program exists" value={p['program-purpose']}/><Field label="Target startup profile" value={p['target-startup-profile']}/></div><div><Field label="Value proposition" value={p['value-proposition']}/><Field label="Explicitly not for" value={p['non-target-profile']||p['not-for']}/></div></div><Note title="Strategic rationale">{p.rationale}</Note></>}
 {tab==='delivery'&&<><h2 className="section-title">Interventions must create evidence.</h2><div className="intervention-list">{resolve(data.interventions,p.interventionIds).map((x,i)=><article key={x.id}><span className="number">{String(i+1).padStart(2,'0')}</span><div><h3>{x.name}</h3><div className="intervention-chain"><div><small>GAP IT CLOSES</small><p>{x.rationale}</p></div><Icon/><div><small>DEVELOPMENT OUTCOME</small><p>{x.outcome}</p></div></div><EditButton collection="interventions" entity={x} onEdit={onEdit}/></div></article>)}</div><h2 className="section-title">Required milestones</h2><MilestoneSequence items={resolve(data.milestones,p.milestoneIds)} onEdit={onEdit}/><h3>Shared capabilities</h3><div className="inline-links">{resolve(data.services,p.serviceIds).map(s=><button key={s.id} onClick={()=>navigate('services/'+s.id)}>{s.name}<Icon/></button>)}</div></>}
 {tab==='gates'&&<><div className="gate-story"><div><small>ENTRY / FIT FOR INTERVENTION</small><h2>{p.entryGateIds.join(' / ')||'Membership'}</h2><p>{p['entry-gates']}</p>{p.entryGateIds.map(g=><button key={g} className="primary" onClick={()=>navigate('gates/'+g)}>Inspect {g} <Icon/></button>)}</div><div className="gate-divider">→</div><div><small>EXIT / VERIFIED DEVELOPMENT</small><h2>{p.exitGateIds.join(' / ')||'Good standing'}</h2><p>{p['exit-gates']}</p>{p.exitGateIds.map(g=><button key={g} className="primary" onClick={()=>navigate('gates/'+g)}>Inspect {g} <Icon/></button>)}</div></div><Note title="Never conflate the three decisions">Completion records participation. Graduation verifies mandatory exit outcomes. Qualification assesses a different program’s entry gate.</Note>{p.entryGateIds.length>0&&<button onClick={()=>navigate('simulator/'+p.entryGateIds[0])}>Check a hypothetical startup <Icon name="check"/></button>}</>}
 {tab==='outcomes'&&<><div className="detail-columns"><div><h2>Expected outcomes</h2>{resolve(data.outcomes,p.outcomeIds).map(x=><div className="field" key={x.id}><p>{x.name}</p><EditButton collection="outcomes" entity={x} onEdit={onEdit}/></div>)}<Field label="Key risks" value={p['key-risks']}/></div><div><h2>Program KPIs</h2>{resolve(data.kpis,p.kpiIds).map(x=><div className="metric-row" key={x.id}><span>{x.name}</span><EditButton collection="kpis" entity={x} onEdit={onEdit}/></div>)}</div></div><Note title="Next-stage routing">{p['next-stage-routing']}</Note><button className="primary" onClick={()=>navigate('routing/'+p.id)}>Trace possible destinations <Icon name="routing"/></button></>}
 <Source section={p.sourceSection}/>
 </>}
export function Comparison({navigate}){const {data}=useFramework();const [selected,setSelected]=useState(['dic','growth']);const ps=data.programs.filter(p=>selected.includes(p.id));const fields=[['Target startup','target-startup-profile'],['Non-target','non-target-profile'],['Maturity at entry','maturity-at-entry'],['Program thesis','program-thesis'],['Entry requirements','entry-gates'],['Intervention thesis','primary-interventions'],['Milestones','required-milestones'],['Exit expectations','exit-gates'],['Outcomes','expected-outcomes'],['KPIs','kpis'],['Next-stage routing','next-stage-routing']];return <><Heading eyebrow="PROGRAM COMPARISON / BOUNDARIES" title="Make the differences explicit." description="Select two or more programs. Compare maturity, intervention purpose and gate expectations side by side."/><div className="compare-options">{data.programs.map(p=><label key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])}/><i style={{background:p.color}}/>{p.shortName}</label>)}</div>{ps.length<2?<Empty text="Select at least two programs to compare."/>:<Table headers={['Dimension',...ps.map(p=><button key={p.id} onClick={()=>navigate('program/'+p.id)}>{p.shortName}<Icon size={14}/></button>)]} rows={fields.map(([label,key])=>[label,...ps.map(p=>key==='primary-interventions'?resolve(data.interventions,p.interventionIds).map(x=>x.name).join('; '):key==='required-milestones'?resolve(data.milestones,p.milestoneIds).map(x=>x.name).join('; '):key==='expected-outcomes'?resolve(data.outcomes,p.outcomeIds).map(x=>x.name).join('; '):key==='kpis'?resolve(data.kpis,p.kpiIds).map(x=>x.name).join('; '):p[key]||'Not specified')])}/>}<Source section="6;16.1"/></>}
