import React,{useEffect,useState,useRef} from 'react';
import {MotionConfig,motion} from 'framer-motion';
import {useFramework} from './lib/context';
import {collections} from './lib/model';
import {Icon,Modal,Note} from './components/common';
import {Overview,Journey,Portfolio} from './components/Journey';
import {ProgramDetail,Comparison} from './components/Programs';
import {Gates,Simulator} from './components/Gates';
import {Routing,Services,KPIs,Logic,Glossary,SourceArchive} from './components/Strategy';
import {Editor,EntityEditor} from './components/Editor';
const nav=[['overview','Overview','overview'],['journey','Startup journey','journey'],['programs','Program portfolio','programs'],['gates','Entry & exit gates','gates'],['simulator','Gate check','check'],['routing','Routing explorer','routing'],['services','Specialist support','routing'],['compare','Compare programs','compare'],['kpis','KPI architecture','kpis'],['logic','Framework logic','logic'],['glossary','Definitions','book'],['source','Full source reference','book']];
const deck=['overview','journey/M0','journey/M2','journey/M5','journey/M7','programs','program/dic','program/growth','program/tasmu','program/scale','gates/E3','gates/X3','routing/growth','services','kpis','logic'];
function useRoute(){const read=()=>location.hash.replace(/^#\/?/,'')||'overview';const [path,setPath]=useState(read);useEffect(()=>{const fn=()=>setPath(read());window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn);},[]);return [path,p=>{location.hash='/'+p;}];}
export default function App(){const {data,edit,setEdit,status}=useFramework();const [path,navigate]=useRoute();const [view,id]=path.split('/');const [editing,setEditing]=useState(null),[present,setPresent]=useState(false),[search,setSearch]=useState(false),[q,setQ]=useState(''),[mobile,setMobile]=useState(false),[editNotice,setEditNotice]=useState(false);const main=useRef();
 const onEdit=(collection,entity,isNew=false)=>setEditing({collection,entity,isNew});
 const go=p=>{navigate(p);setMobile(false);};
 useEffect(()=>{main.current?.scrollTo(0,0);requestAnimationFrame(()=>main.current?.querySelector('h1')?.focus());},[path]);
 const slide=deck.indexOf(path);
 const step=delta=>go(deck[Math.max(0,Math.min(deck.length-1,(slide<0?0:slide)+delta))]);
 useEffect(()=>{const fn=e=>{if(e.target.closest('input,textarea,select,dialog'))return;if(present){if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();step(1);}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();step(-1);}if(e.key==='Escape'){setPresent(false);if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});}}if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setSearch(true);}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[present,path]);
 function startPresentation(){setEdit(false);setEditing(null);setPresent(true);go('overview');}
 const common={id,navigate:go,onEdit};let content;
 switch(view){case 'journey':content=<Journey {...common}/>;break;case 'programs':content=<Portfolio {...common}/>;break;case 'program':content=<ProgramDetail key={id} {...common}/>;break;case 'gates':content=<Gates {...common}/>;break;case 'simulator':content=<Simulator {...common}/>;break;case 'routing':content=<Routing {...common}/>;break;case 'services':content=<Services {...common}/>;break;case 'compare':content=<Comparison {...common}/>;break;case 'kpis':content=<KPIs {...common}/>;break;case 'logic':content=<Logic {...common}/>;break;case 'glossary':content=<Glossary {...common}/>;break;case 'source':content=<SourceArchive/>;break;case 'editor':content=<Editor {...common}/>;break;default:content=<Overview {...common}/>;}
 const results=q.trim()?collections.flatMap(k=>data[k].filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())).map(x=>({collection:k,entity:x}))).slice(0,35):[];
 function resultRoute(k,x){return k==='programs'?'program/'+x.id:k==='stages'?'journey/'+x.id:k==='gates'?'gates/'+x.id:k==='criteria'?'gates/'+x.gateId:k==='services'?'services/'+x.id:k==='routes'?'routing/'+(x.fromId==='Any'?'dic':x.fromId):['interventions','milestones','outcomes'].includes(k)?'program/'+x.programId:k==='kpis'?'kpis':k==='glossary'?'glossary':'logic';}
 return <MotionConfig reducedMotion="user"><div className={`app ${present?'presentation':''} ${mobile?'mobile-nav':''}`}><a className="skip-link" href="#main">Skip to content</a><aside className="sidebar"><div className="brand"><span className="brand-mark">M</span><div><strong>MCIT</strong><small>DIGITAL INNOVATION<br/>ENABLEMENT</small></div></div><div className="sidebar-label">ARCHITECTURE STUDIO</div><nav aria-label="Main navigation">{nav.map(([key,label,icon])=><a key={key} href={'#/'+key} className={(view===key||key==='programs'&&view==='program')?'active':''} aria-current={view===key?'page':undefined} onClick={()=>setMobile(false)}><Icon name={icon}/>{label}</a>)}</nav><div className="sidebar-bottom"><a href="#/editor"><Icon name="edit"/>Framework studio</a><p>One record.<br/>One maturity language.<br/>Independent gates.</p><small>Source-backed · Local-first</small></div></aside><div className="workspace"><header className="topbar"><button className="menu-button" onClick={()=>setMobile(x=>!x)} aria-label="Toggle navigation"><Icon name="programs"/></button><div className="breadcrumb"><button onClick={()=>go('overview')}>Portfolio</button><span>/</span><strong>{nav.find(n=>n[0]===view)?.[1]||'Program architecture'}</strong>{id&&<><span>/</span><span>{id}</span></>}</div><div className="top-actions">{!present&&<><button className="icon-button" onClick={()=>setSearch(true)} aria-label="Search framework"><Icon name="search"/></button><button className={edit?'mode active':'mode'} onClick={()=>{if(edit)setEdit(false);else setEditNotice(true);}}><Icon name="edit"/>{edit?'Edit mode':'View mode'}</button><button onClick={startPresentation}><Icon name="present"/>Present</button></>}{present&&<><button onClick={()=>document.documentElement.requestFullscreen?.().catch(()=>{})}>Fullscreen</button><button onClick={()=>{setPresent(false);if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});}}>Exit presentation</button></>}</div></header><main id="main" ref={main}><motion.div key={view} className="view" initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.16}}>{content}</motion.div><footer className="workspace-footer"><span>{data.meta.subtitle}</span><span aria-live="polite">{status} · Revision {data.meta.revision}</span></footer></main>{present&&<div className="presentation-nav"><button onClick={()=>step(-1)} disabled={slide===0}>← Previous</button><span>{slide<0?'Explore':String(slide+1).padStart(2,'0')} / {deck.length} <small>Arrow keys to navigate · Esc to exit</small></span><button onClick={()=>step(1)} disabled={slide===deck.length-1}>Next →</button></div>}</div></div>
 {editing&&edit&&!present&&<EntityEditor {...editing} onClose={()=>setEditing(null)}/>}
 {editNotice&&<Modal title="Enable local editing" onClose={()=>setEditNotice(false)}><Note title="This is a local workspace, not a secure shared system">Changes are stored in this browser only. Edit mode does not authenticate users. Export revisions for backup or transfer; do not enter confidential startup data.</Note><button className="primary" onClick={()=>{setEdit(true);setEditNotice(false);}}>Enable Edit mode <Icon name="edit"/></button></Modal>}
 {search&&<Modal title="Search the framework" onClose={()=>{setSearch(false);setQ('');}} wide><label className="search-box"><Icon name="search"/><input autoFocus aria-label="Search framework content" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search a stage, program, criterion, service or rationale"/></label><div className="search-results">{results.map(({collection:k,entity:x})=><button key={k+x.id} onClick={()=>{go(resultRoute(k,x));setSearch(false);setQ('');}}><small>{k} · {x.id}</small><strong>{x.name}</strong><Icon/></button>)}{q&&!results.length&&<p>No matches. Try the full source reference for additional wording.</p>}</div></Modal>}
 </MotionConfig>;
}
